"""Initial AutoGrid360 schema

Revision ID: 98b97bf7aa67
Revises: 
Create Date: 2026-08-18 23:25:28.499942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b97bf7aa67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_autogrid360_postal_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('locality', sa.String(length=180), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('region_code', sa.String(length=20), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_plugin_autogrid360_postal_latitude'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_plugin_autogrid360_postal_longitude'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'postal_code', name='uq_plugin_autogrid360_postal_country_code')
    )
    with op.batch_alter_table('plugin_autogrid360_postal_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_postal_locations_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_postal_locations_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_postal_locations_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_postal_locations_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_postal_locations_postal_code'), ['postal_code'], unique=False)

    op.create_table('plugin_autogrid360_reference_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('default_selected', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'key', name='uq_plugin_autogrid360_reference_value_category_key')
    )
    with op.batch_alter_table('plugin_autogrid360_reference_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_reference_values_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_reference_values_category'), ['category'], unique=False)

    op.create_table('plugin_autogrid360_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('require_listing_approval', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('require_rereview_on_edit', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('enable_listing_expiration', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('listing_expiration_days', sa.Integer(), server_default='60', nullable=False),
    sa.Column('expiration_warning_days', sa.Integer(), server_default='7', nullable=False),
    sa.Column('expired_retention_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('expired_removal_warning_days', sa.Integer(), server_default='7', nullable=False),
    sa.Column('show_sale_pending_listings_publicly', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('show_sold_listings_publicly', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('sold_retention_days', sa.Integer(), server_default='90', nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('currency_symbol', sa.String(length=8), server_default='$', nullable=False),
    sa.Column('currency_decimal_separator', sa.String(length=1), server_default='.', nullable=False),
    sa.Column('currency_thousands_separator', sa.String(length=1), server_default=',', nullable=False),
    sa.Column('default_distance_unit', sa.String(length=16), server_default='auto', nullable=False),
    sa.Column('listing_images_path', sa.String(length=255), server_default='uploads/listings', nullable=False),
    sa.Column('allow_seller_inventory_import', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency_decimal_separator IN ('.', ',')", name='ck_autogrid360_settings_currency_decimal_separator'),
    sa.CheckConstraint("currency_thousands_separator = '' OR currency_thousands_separator <> currency_decimal_separator", name='ck_autogrid360_settings_currency_separators_distinct'),
    sa.CheckConstraint("currency_thousands_separator IN (',', '.', ' ', '')", name='ck_autogrid360_settings_currency_thousands_separator'),
    sa.CheckConstraint("default_distance_unit IN ('auto', 'miles', 'kilometers')", name='ck_autogrid360_settings_default_distance_unit'),
    sa.CheckConstraint('expiration_warning_days < listing_expiration_days', name='ck_autogrid360_settings_warning_before_expiration'),
    sa.CheckConstraint('expiration_warning_days >= 0', name='ck_autogrid360_settings_warning_days_nonnegative'),
    sa.CheckConstraint('expired_removal_warning_days < expired_retention_days', name='ck_autogrid360_settings_removal_warning_before_archive'),
    sa.CheckConstraint('expired_removal_warning_days >= 0', name='ck_autogrid360_settings_removal_warning_days_nonnegative'),
    sa.CheckConstraint('expired_retention_days >= 1', name='ck_autogrid360_settings_expired_retention_days_positive'),
    sa.CheckConstraint('length(currency_code) = 3', name='ck_autogrid360_settings_currency_code_length'),
    sa.CheckConstraint('listing_expiration_days >= 1', name='ck_autogrid360_settings_expiration_days_positive'),
    sa.CheckConstraint('sold_retention_days >= 0', name='ck_autogrid360_settings_sold_retention_days_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plugin_autogrid360_seller_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plugin_autogrid360_seller_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_seller_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('plugin_autogrid360_vehicle_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['plugin_autogrid360_reference_values.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('make_id', 'key', name='uq_plugin_autogrid360_vehicle_model_make_key')
    )
    with op.batch_alter_table('plugin_autogrid360_vehicle_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_vehicle_models_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_vehicle_models_make_id'), ['make_id'], unique=False)

    op.create_table('plugin_autogrid360_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('model_text', sa.String(length=80), nullable=True),
    sa.Column('trim', sa.String(length=80), nullable=True),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('doors', sa.SmallInteger(), nullable=True),
    sa.Column('exterior_color', sa.String(length=50), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=30), nullable=True),
    sa.Column('engine', sa.String(length=80), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('drivetrain_id', sa.Integer(), nullable=True),
    sa.Column('mpg', sa.SmallInteger(), nullable=True),
    sa.Column('fuel_type', sa.String(length=30), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('stock_number', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(model_id IS NOT NULL AND model_text IS NULL) OR (model_id IS NULL AND model_text IS NOT NULL)', name='ck_plugin_autogrid360_vehicle_model_source'),
    sa.ForeignKeyConstraint(['drivetrain_id'], ['plugin_autogrid360_reference_values.id'], ),
    sa.ForeignKeyConstraint(['make_id'], ['plugin_autogrid360_reference_values.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['plugin_autogrid360_vehicle_models.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['plugin_autogrid360_reference_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plugin_autogrid360_vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_vehicles_drivetrain_id'), ['drivetrain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_vehicles_make_id'), ['make_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_vehicles_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_vehicles_model_text'), ['model_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_vehicles_vehicle_type_id'), ['vehicle_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_vehicles_vin'), ['vin'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_vehicles_year'), ['year'], unique=False)

    op.create_table('plugin_autogrid360_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portable_id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('featured', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zone_code', sa.String(length=16), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('postal_location_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('first_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_warning_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_removal_warning_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aged_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aged_out_notice_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['postal_location_id'], ['plugin_autogrid360_postal_locations.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['plugin_autogrid360_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plugin_autogrid360_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_listings_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_listings_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_listings_portable_id'), ['portable_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_listings_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_listings_postal_location_id'), ['postal_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_listings_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_listings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_listings_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_listings_zone_code'), ['zone_code'], unique=False)

    op.create_table('plugin_autogrid360_vehicle_features',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('reference_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_value_id'], ['plugin_autogrid360_reference_values.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['plugin_autogrid360_vehicles.id'], ),
    sa.PrimaryKeyConstraint('vehicle_id', 'reference_value_id')
    )
    op.create_table('plugin_autogrid360_listing_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['plugin_autogrid360_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key'),
    sa.UniqueConstraint('thumbnail_key')
    )
    with op.batch_alter_table('plugin_autogrid360_listing_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugin_autogrid360_listing_images_listing_id'), ['listing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin_autogrid360_listing_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_listing_images_listing_id'))

    op.drop_table('plugin_autogrid360_listing_images')
    op.drop_table('plugin_autogrid360_vehicle_features')
    with op.batch_alter_table('plugin_autogrid360_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_listings_zone_code'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_listings_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_listings_status'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_listings_seller_id'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_listings_postal_location_id'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_listings_postal_code'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_listings_portable_id'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_listings_country_code'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_listings_city'))

    op.drop_table('plugin_autogrid360_listings')
    with op.batch_alter_table('plugin_autogrid360_vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_vehicles_year'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_vehicles_vin'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_vehicles_vehicle_type_id'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_vehicles_model_text'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_vehicles_model_id'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_vehicles_make_id'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_vehicles_drivetrain_id'))

    op.drop_table('plugin_autogrid360_vehicles')
    with op.batch_alter_table('plugin_autogrid360_vehicle_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_vehicle_models_make_id'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_vehicle_models_active'))

    op.drop_table('plugin_autogrid360_vehicle_models')
    with op.batch_alter_table('plugin_autogrid360_seller_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_seller_profiles_user_id'))

    op.drop_table('plugin_autogrid360_seller_profiles')
    op.drop_table('plugin_autogrid360_settings')
    with op.batch_alter_table('plugin_autogrid360_reference_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_reference_values_category'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_reference_values_active'))

    op.drop_table('plugin_autogrid360_reference_values')
    with op.batch_alter_table('plugin_autogrid360_postal_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_postal_locations_postal_code'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_postal_locations_longitude'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_postal_locations_latitude'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_postal_locations_country_code'))
        batch_op.drop_index(batch_op.f('ix_plugin_autogrid360_postal_locations_active'))

    op.drop_table('plugin_autogrid360_postal_locations')
    # ### end Alembic commands ###
